$RNFirebaseAsStaticFramework = true
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
# flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# Handle static framework conflict for Flipper + Swift pods
$static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
  'CocoaAsyncSocket', 'ComponentKit', 'Flipper-DoubleConversion',
  'Flipper-Glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
  'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']

pre_install do |installer|
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
	installer.pod_targets.each do |pod|
	  if $static_framework.include?(pod.name)
		def pod.build_type;
		  Pod::BuildType.static_library
		end
	  end
	end
end

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'propertyLenzApp' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # 👉 Add RNPhotoEditor & iOSPhotoEditor pods here
  pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'
  pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor', :branch => 'master'


  target 'propertyLenzAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

	# 👉 Set Swift version for iOSPhotoEditor
    installer.pods_project.targets.each do |pod_target|
		if pod_target.name.include?('iOSPhotoEditor')
		  pod_target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '5'
		  end
		end
	end

	# 🚫 Disable automatic resource copy that causes cycle
  installer.pods_project.targets.each do |pod_target|
    next unless pod_target.respond_to?(:resources_build_phase)
    
    pod_target.resources_build_phase.files.each do |file|
		if file.file_ref && file.file_ref.path && file.file_ref.path.include?('AntDesign.ttf')
		  file.remove_from_project
		end
	end
end

  end
end
